"""agregar pais dispositivo navegador a visitas

Revision ID: 6fcedb4b1d37
Revises: 99377e5e3f57
Create Date: 2026-07-08 20:13:39.072475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcedb4b1d37'
down_revision: Union[str, Sequence[str], None] = '99377e5e3f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitas', sa.Column('pais', sa.String(length=100), nullable=True))
    op.add_column('visitas', sa.Column('dispositivo', sa.String(length=50), nullable=True))
    op.add_column('visitas', sa.Column('navegador', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitas', 'navegador')
    op.drop_column('visitas', 'dispositivo')
    op.drop_column('visitas', 'pais')
    # ### end Alembic commands ###
