"""crear tablas urls y visitas

Revision ID: 99377e5e3f57
Revises: 
Create Date: 2026-07-04 16:30:32.171300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99377e5e3f57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_larga', sa.Text(), nullable=False),
    sa.Column('url_corta', sa.String(length=10), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_url_corta'), 'urls', ['url_corta'], unique=True)
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_usuario', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas')
    op.drop_index(op.f('ix_urls_url_corta'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
